FROM openjdk:11

MAINTAINER Pedro Miguel Rodriguez <petermichael85@gmail.com>

EXPOSE 8081

COPY /target/dkhService2*.jar dkhService2.jar

ENTRYPOINT java -jar dkhService2.jar

####################################################################
# docker build -f Dockerfile -t petermichael85/dkhservice2:0.0.1 .
#
# docker push petermichael85/dkhservice2
#