version: '3'

networks: 
  backend:
  
services:
  dkhservice1:
    image: petermichael85/dkhservice1:0.0.2
    build: ./dkhService1
    container_name: dkhservice1
    ports:
     - "8080:8080"
    environment:
     - DKHSERVICE2_PATH=http://dkhservice2:8081
    networks: 
      - backend

  dkhservice2:
    image: petermichael85/dkhservice2:0.0.1
    build: ./dkhService2
    container_name: dkhservice2
    ports:
     - "8081:8081"
    networks: 
     - backend

#####################################
# docker-compose up
#
# http://localhost:8080/live/ready
# http://localhost:8080/live/healthy
# http://localhost:8080/live/kill
# http://localhost:8080/hello
#