version: '3'
services:
  dkhservice1:
    image: dkhservice1
    build: ./dkh_service1
    container_name: dkhservice1
    ports:
     - "8080:8080"

#####################################
# docker-compose up
#
# http://localhost:8080/live/ready
# http://localhost:8080/live/healthy
# http://localhost:8080/live/kill
# http://localhost:8080/hello
#