FROM openjdk:11

MAINTAINER Pedro Miguel Rodriguez <petermichael85@gmail.com>

EXPOSE 8080

COPY /target/dkhService1*.jar dkhService1.jar

ENTRYPOINT java -jar dkhService1.jar

####################################################################
# docker build -f Dockerfile -t petermichael85/dkhservice1:0.0.2 .
#
# docker push petermichael85/dkhservice1
#