apiVersion: apps/v1
kind: Deployment
metadata:
  name: dkhservice2-dpl
spec:
  replicas: 2
  selector:
    matchLabels:
      app-name: dkhservice2
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  
  template:
    metadata:
      name: dkhservice2-pod
      labels:
        type: back-end
        app-name: dkhservice2
        language: java
    spec:
      containers:
      - name: dkhservice2
        image: petermichael85/dkhservice2:0.0.2
        #imagePullPolicy: Always
        ports:
        - name: default-port
          containerPort: 8081
        envFrom:
        - secretRef:
            name: mysql-sec
        readinessProbe:
          httpGet:
            path: /live/healthy
            port: default-port
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /live/healthy
            port: default-port
          initialDelaySeconds: 120
          periodSeconds: 5
          failureThreshold: 2
        resources:
          requests:
            cpu: .1
            memory: "256Mi"
          limits:
            cpu: .2
            memory: "500Mi"            

---

apiVersion: v1
kind: Service
metadata:
  name: dkhservice2-svc
spec:
  selector:
    app-name: dkhservice2
  type: NodePort
  ports:
  - targetPort: 8081
    port: 8080
