apiVersion: apps/v1
kind: Deployment
metadata:
  name: dkhservice1-dpl
spec:
  replicas: 2
  selector:
    matchLabels:
      type: back-end
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  
  template:
    metadata:
      name: dkhservice1-pod
      labels:
        type: back-end
        language: java
    spec:
      containers:
      - name: dkhservice1
        image: petermichael85/dkhservice1:0.0.1
        ports:
        - name: default-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /live/healthy
            port: default-port
          initialDelaySeconds: 40
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /live/healthy
            port: default-port
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 2
        resources:
          requests:
            cpu: .1
            memory: "256Mi"
          limits:
            cpu: .2
            memory: "500Mi"            
---

apiVersion: v1
kind: Service
metadata:
  name: dkhservice1-svc
spec:
  selector:
    type: back-end
  type: NodePort
  ports:
  - targetPort: 8080
    port: 8080
    nodePort: 30008
  

###################################
# kubectl get node -o wide
#
# http://node-ip:30008/hello
#