version: '3'

networks: 
  backend:
  
services:
  dkhservice1:
    image: petermichael85/dkhservice1:0.0.5
    build: ../dkhService1
    container_name: dkhservice1
    ports:
     - "8080:8080"
    environment:
     - DKHSERVICE2_PATH=http://dkhservice2:8081
     - showHostname=true
     - HOSTNAME=Docker
    networks: 
     - backend

  dkhservice2:
    image: petermichael85/dkhservice2:0.0.3
    build: ../dkhService2
    container_name: dkhservice2
    ports:
     - "8081:8081"
    environment:
     - MYSQL_HOST=mysql
     - MYSQL_PORT=3306
     - MYSQL_USER=root
     - MYSQL_PWD=my-secret-pw
    depends_on:
      - mysql
    networks: 
     - backend

  dkhgeodeapi:
    image: petermichael85/dkhgeodeapi:0.0.1
    build: ../dkhGeodeapi
    container_name: dkhgeodeapi
    ports:
     - "8082:8082"
    environment:
     - GEODE_HOST=localhost
     - GEODE_PORT=40404
    depends_on:
     - geode
    networks: 
     - backend

  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
     - MYSQL_DATABASE=dkh
    volumes: 
     - mysql-data-vol:/var/lib/mysql
    ports:
     - "3306:3306"
    networks:
     - backend

  geode:
    image: petermichael85/dkhgeodeserver:0.0.1
    container_name: geode
    ports:
     - "10334:10334"
     - "40404:40404"
    networks:
     - backend

volumes:
  mysql-data-vol:



#####################################
# docker-compose up
#
# http://localhost:8080/live/ready
# http://localhost:8080/live/healthy
# http://localhost:8080/live/kill
# http://localhost:8080/hello
#

#SHOW DATABASES;
#USE dkh;
#SHOW TABLES;
#CREATE TABLE `person` (`Id` INTEGER, `Name` VARCHAR(20), `Surname` VARCHAR(20), `Age` INTEGER);
#INSERT INTO person(Id, Name, Surname, Age) VALUES (1, 'Juan', 'Rodriguez', 35);



#docker container run -it -p 10334:10334 -p 40404:40404 --name geode apachegeode/geode:1.12.0 /bin/bash
#gfsh> list members
#gfsh> create region --name=dkh --type=REPLICATE
#gfsh> create region --name=tracking --type=REPLICATE
#gfsh> describe region --name=dkh
#gfsh> query --query='select e.key, e.value from /dkh.entries e'