version: '3'

networks: 
  backend:
  
services:
  dkhservice1:
    image: petermichael85/dkhservice1:0.0.5
    build: ../dkhService1
    container_name: dkhservice1
    ports:
     - "8080:8080"
    environment:
     - DKHSERVICE2_PATH=http://dkhservice2:8081
     - showHostname=true
     - HOSTNAME=Docker
    networks: 
     - backend

  dkhservice2:
    image: petermichael85/dkhservice2:0.0.3
    build: ../dkhService2
    container_name: dkhservice2
    ports:
     - "8081:8081"
    environment:
     - MYSQL_HOST=mysql
     - MYSQL_PORT=3306
     - MYSQL_USER=root
     - MYSQL_PWD=my-secret-pw
    depends_on:
      - mysql
    networks: 
     - backend

  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
     - MYSQL_DATABASE=dkh
    volumes: 
     - mysql-data-vol:/var/lib/mysql
    ports:
     - "3306:3306"
    networks:
     - backend
     
volumes:
  mysql-data-vol:
 
#####################################
# docker-compose up
#
# http://localhost:8080/live/ready
# http://localhost:8080/live/healthy
# http://localhost:8080/live/kill
# http://localhost:8080/hello
#

#SHOW DATABASES;
#USE dkh;
#SHOW TABLES;
#CREATE TABLE `person` (`Id` INTEGER, `Name` VARCHAR(20), `Surname` VARCHAR(20), `Age` INTEGER);
#INSERT INTO person(Id, Name, Surname, Age) VALUES (1, 'Juan', 'Rodriguez', 35);
