FROM openjdk:11.0.6-jre

MAINTAINER Pedro Miguel Rodriguez <petermichael85@gmail.com>

COPY /target/dkhCronjob*.jar dkhCronjob.jar

ENTRYPOINT java -jar dkhCronjob.jar

####################################################################
# docker build -f Dockerfile -t petermichael85/dkhcronjob:0.0.1 .
#
# docker push petermichael85/dkhcronjob:0.0.1
#