apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    type: bbdd
    app-name: mysql
spec:
  containers:
  - name: mysql
    image: {{ .Values.mysql.image }}
    ports:
     - containerPort: {{ .Values.mysql.ports.containerPort }}
    env:
     - name: MYSQL_ROOT_PASSWORD
       valueFrom:
         secretKeyRef:
           name: mysql-sec
           key: MYSQL_PWD
     - name: MYSQL_DATABASE
       valueFrom:
         secretKeyRef:
           name: mysql-sec
           key: MYSQL_DATABASE
    volumeMounts:
     - name: mysql-data-vol
       mountPath: /var/lib/mysql
      
  volumes:
  - name: mysql-data-vol
    persistentVolumeClaim:
      claimName: claim-mysql