apiVersion: v1
kind: Service
metadata:
  name: dkhservice1-svc
spec:
  selector:
    app-name: dkhservice1
  type: NodePort
  ports:
  - targetPort: 8080
    port: 8080
    nodePort: 30008

---

apiVersion: v1
kind: Service
metadata:
  name: dkhservice2-svc
spec:
  selector:
    app-name: dkhservice2
  type: NodePort
  ports:
  - targetPort: 8081
    port: 8080

