apiVersion: v1
kind: Service
metadata:
  name: dkhservice1-svc
spec:
  selector:
    app-name: dkhservice1
  type: NodePort
  ports:
  - targetPort: {{ .Values.dkhservice1.ports.containerPort }}
    port: {{ .Values.dkhservice1.ports.servicePort }}
    nodePort: {{ .Values.dkhservice1.ports.nodePort }}

---

apiVersion: v1
kind: Service
metadata:
  name: dkhservice2-svc
spec:
  selector:
    app-name: dkhservice2
  type: NodePort
  ports:
  - targetPort: {{ .Values.dkhservice2.ports.containerPort }}
    port: {{ .Values.dkhservice2.ports.servicePort }}

